# Generated by Django 5.2.7 on 2025-10-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_factory_key_car_factory_year_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(default='Marca Indefinida', max_length=200),
        ),
    ]
