# Generated by Django 5.2.7 on 2025-10-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_brand_alter_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
