# Generated by Django 5.2.7 on 2025-10-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='plate_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
